/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.dialogs;

/**
 *
 * @author Darko
 */
public class CreateMatrixDialog extends javax.swing.JDialog {

    /**
     * Creates new form EnterMatrixDialog
     */
    public CreateMatrixDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEnterMatrixName = new javax.swing.JLabel();
        jtfEnterMatrixName = new javax.swing.JTextField();
        jlblEnterNbrRows = new javax.swing.JLabel();
        jtfEnterNbrRows = new javax.swing.JTextField();
        jlblEnterNbrColumns = new javax.swing.JLabel();
        jtfEnterNbrColumns = new javax.swing.JTextField();
        jlblCreateMatrixTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnCancel = new javax.swing.JButton();
        jbtnCreate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        setTitle(bundle.getString("CreateMatrixDialog.title")); // NOI18N
        setModal(true);
        setResizable(false);

        jlblEnterMatrixName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblEnterMatrixName.setText(bundle.getString("CreateMatrixDialog.jlblEnterMatrixName.text")); // NOI18N

        jtfEnterMatrixName.setText(bundle.getString("CreateMatrixDialog.jtfEnterMatrixName.text")); // NOI18N

        jlblEnterNbrRows.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblEnterNbrRows.setText(bundle.getString("CreateMatrixDialog.jlblEnterNbrRows.text")); // NOI18N

        jtfEnterNbrRows.setText(bundle.getString("CreateMatrixDialog.jtfEnterNbrRows.text")); // NOI18N

        jlblEnterNbrColumns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblEnterNbrColumns.setText(bundle.getString("CreateMatrixDialog.jlblEnterNbrColumns.text")); // NOI18N

        jtfEnterNbrColumns.setText(bundle.getString("CreateMatrixDialog.jtfEnterNbrColumns.text")); // NOI18N

        jlblCreateMatrixTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblCreateMatrixTitle.setText(bundle.getString("CreateMatrixDialog.jlblCreateMatrixTitle.text")); // NOI18N

        jbtnCancel.setText(bundle.getString("CreateMatrixDialog.jbtnCancel.text")); // NOI18N
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnCreate.setText(bundle.getString("CreateMatrixDialog.jbtnCreate.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblEnterNbrRows)
                            .addComponent(jlblEnterMatrixName))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEnterMatrixName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfEnterNbrRows, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 189, Short.MAX_VALUE))))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblEnterNbrColumns)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEnterNbrColumns, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblCreateMatrixTitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblCreateMatrixTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEnterMatrixName)
                    .addComponent(jtfEnterMatrixName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEnterNbrRows)
                    .addComponent(jtfEnterNbrRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEnterNbrColumns)
                    .addComponent(jtfEnterNbrColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnCreate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnCreate;
    private javax.swing.JLabel jlblCreateMatrixTitle;
    private javax.swing.JLabel jlblEnterMatrixName;
    private javax.swing.JLabel jlblEnterNbrColumns;
    private javax.swing.JLabel jlblEnterNbrRows;
    private javax.swing.JTextField jtfEnterMatrixName;
    private javax.swing.JTextField jtfEnterNbrColumns;
    private javax.swing.JTextField jtfEnterNbrRows;
    // End of variables declaration//GEN-END:variables
}
