/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.dialogs;

import hummingmatrix.v2.models.MatrixComboBoxModel;
import hummingmatrix.v2.panels.MatrixFrame;
import java.awt.Frame;
import java.util.ResourceBundle;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Darko
 */
public class OpenMatrixDialog extends javax.swing.JDialog {

    private MatrixComboBoxModel matrixModel = new MatrixComboBoxModel();
    private ResourceBundle bundle = ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle");
    private java.awt.Frame parent;

    /**
     * Creates new form OpenMatrixDialog
     */
    public OpenMatrixDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOpenMatrixTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlblSelectMatrix = new javax.swing.JLabel();
        jcbSelectMatrix = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnCancel = new javax.swing.JButton();
        jbtnOpenMatrix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        setTitle(bundle.getString("OpenMatrixDialog.title")); // NOI18N
        setResizable(false);

        jlblOpenMatrixTitle.setFont(new java.awt.Font("Tahoma", 0, 18));
        jlblOpenMatrixTitle.setText(bundle.getString("OpenMatrixDialog.jlblOpenMatrixTitle.text")); // NOI18N

        jlblSelectMatrix.setFont(new java.awt.Font("Tahoma", 0, 14));
        jlblSelectMatrix.setText(bundle.getString("OpenMatrixDialog.jlblSelectMatrix.text")); // NOI18N

        jcbSelectMatrix.setModel(matrixModel);

        jbtnCancel.setText(bundle.getString("OpenMatrixDialog.jbtnCancel.text")); // NOI18N
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnOpenMatrix.setText(bundle.getString("OpenMatrixDialog.jbtnOpenMatrix.text")); // NOI18N
        jbtnOpenMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpenMatrixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblSelectMatrix)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSelectMatrix, 0, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblOpenMatrixTitle)
                        .addGap(0, 284, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addComponent(jbtnOpenMatrix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOpenMatrixTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSelectMatrix)
                    .addComponent(jcbSelectMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnOpenMatrix))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

private void jbtnOpenMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpenMatrixActionPerformed
    // TODO add your handling code here
    if (jcbSelectMatrix.getSelectedItem() == null) {
        WarningDialog wd = new WarningDialog(null, true, bundle.getString("WarningMsg.pleaseSelectMatrix.text"));
        jcbSelectMatrix.requestFocus();
        return;
    }
    //Adding MatrixFrame
    parent.setState(Frame.ICONIFIED);
    MatrixFrame mf = new MatrixFrame(jcbSelectMatrix.getSelectedItem().toString());
    mf.setWestPanelHolder();
    mf.setEastPanelHolder();
    mf.setLocationRelativeTo(this);
    mf.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jbtnOpenMatrixActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOpenMatrix;
    private javax.swing.JComboBox jcbSelectMatrix;
    private javax.swing.JLabel jlblOpenMatrixTitle;
    private javax.swing.JLabel jlblSelectMatrix;
    // End of variables declaration//GEN-END:variables
}
