/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

import hummingmatrix.v2.classes.ReadWriteText;
import hummingmatrix.v2.interfaces.CalculateMatrixObserver;
import hummingmatrix.v2.interfaces.CalculateMatrixSubject;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Darko
 */
public class ActionsPanel extends javax.swing.JPanel implements CalculateMatrixSubject{

    private ReadWriteText matrixObj;
    private List<CalculateMatrixObserver> observers = new ArrayList<CalculateMatrixObserver>();
    
    /**
     * Creates new form ActionsPanel
     */
    public ActionsPanel(ReadWriteText matrix) {
        initComponents();
        this.matrixObj = matrix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCalculateMatrix = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        jbtnCalculateMatrix.setText(bundle.getString("btn.Calculate")); // NOI18N
        jbtnCalculateMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalculateMatrixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCalculateMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCalculateMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalculateMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalculateMatrixActionPerformed
        notifyObservers();
    }//GEN-LAST:event_jbtnCalculateMatrixActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtnCalculateMatrix;
    // End of variables declaration//GEN-END:variables

    @Override
    public void register(CalculateMatrixObserver obj) {
        if (obj == null) {
            throw new NullPointerException("Null Observer");
        }
        observers.add(obj);
        
    }

    @Override
    public void unregister(CalculateMatrixObserver obj) {
        observers.remove(obj);
    }

    @Override
    public void notifyObservers() {
        for (CalculateMatrixObserver obj: observers) {
            obj.onCalculate();
        }
    }
}
