/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

import hummingmatrix.v2.classes.ReadWriteText;

/**
 *
 * @author Ane
 */
public class EastPanelHolder extends javax.swing.JPanel {
    
    private ReadWriteText matrixObj;

    /**
     * Creates new form WestPanelHolder
     */
    public EastPanelHolder(ReadWriteText matrix) {
        initComponents();
        this.matrixObj = matrix;
        
    }
    
    public void addResultsPanel() {
        ResultsPanel rp = new ResultsPanel(this.matrixObj);
        this.add(rp);
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
