/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

import hummingmatrix.v2.dialogs.CreateMatrixDialog;
import hummingmatrix.v2.dialogs.NoMatrixEnteredAlertDialog;
import hummingmatrix.v2.dialogs.OpenMatrixDialog;
import hummingmatrix.v2.models.MatrixComboBoxModel;

/**
 *
 * @author Aneta
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        miCreateNewMatrix = new javax.swing.JMenuItem();
        miOpenMatrix = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        setTitle(bundle.getString("jFrame.title")); // NOI18N

        fileMenu.setMnemonic('m');
        fileMenu.setText(bundle.getString("menu.item.Matrix")); // NOI18N

        miCreateNewMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miCreateNewMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/new.png"))); // NOI18N
        miCreateNewMatrix.setMnemonic('n');
        miCreateNewMatrix.setText(bundle.getString("menu.item.create_new_matrix")); // NOI18N
        miCreateNewMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateNewMatrixActionPerformed(evt);
            }
        });
        fileMenu.add(miCreateNewMatrix);

        miOpenMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpenMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/open.png"))); // NOI18N
        miOpenMatrix.setMnemonic('o');
        miOpenMatrix.setText(bundle.getString("menu.item.open_matrix")); // NOI18N
        miOpenMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenMatrixActionPerformed(evt);
            }
        });
        fileMenu.add(miOpenMatrix);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText(bundle.getString("menu.item.exit")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText(bundle.getString("HomeFrame.helpMenu.text")); // NOI18N

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText(bundle.getString("HomeFrame.aboutMenuItem.text")); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void miCreateNewMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateNewMatrixActionPerformed
        CreateMatrixDialog cmd = new CreateMatrixDialog(this, true);
        cmd.setLocationRelativeTo(this);
        cmd.setVisible(true);
    }//GEN-LAST:event_miCreateNewMatrixActionPerformed

    private void miOpenMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenMatrixActionPerformed
        //Check if matrices exiist. If not show alert box.
        MatrixComboBoxModel mcbm = new MatrixComboBoxModel();
        if (mcbm.getSize() > 0) {
            OpenMatrixDialog omd = new OpenMatrixDialog(this, true);
            omd.setLocationRelativeTo(this);
            omd.setVisible(true);
        } else {
            NoMatrixEnteredAlertDialog nmed = new NoMatrixEnteredAlertDialog(this, true);
            nmed.setLocationRelativeTo(this);
            nmed.setVisible(true);
        }
    }//GEN-LAST:event_miOpenMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCreateNewMatrix;
    private javax.swing.JMenuItem miOpenMatrix;
    // End of variables declaration//GEN-END:variables
}
