/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MatrixFrame.java
 *
 * Created on Mar 10, 2013, 12:32:36 AM
 */
package hummingmatrix.v2.panels;

/**
 *
 * @author Ane
 */
public class MatrixFrame extends javax.swing.JFrame {

    /** Creates new form MatrixFrame */
    public MatrixFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmMatrix = new javax.swing.JMenu();
        jmiCreateNewMatrix = new javax.swing.JMenuItem();
        jmiOpenMatrix = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiSaveMatrix = new javax.swing.JMenuItem();
        jmiSaveAsMatrix = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiDeleteMatrix = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmExport = new javax.swing.JMenu();
        jmiToExcel = new javax.swing.JMenuItem();
        jmiToPdf = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiClose = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();
        jmiTransposeMatrix = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jmMatrix.setMnemonic('m');
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        jmMatrix.setText(bundle.getString("MatrixFrame.jmMatrix.text")); // NOI18N

        jmiCreateNewMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmiCreateNewMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/new.png"))); // NOI18N
        jmiCreateNewMatrix.setMnemonic('n');
        jmiCreateNewMatrix.setText(bundle.getString("MatrixFrame.jmiCreateNewMatrix.text")); // NOI18N
        jmiCreateNewMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateNewMatrixActionPerformed(evt);
            }
        });
        jmMatrix.add(jmiCreateNewMatrix);

        jmiOpenMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/open.png"))); // NOI18N
        jmiOpenMatrix.setMnemonic('o');
        jmiOpenMatrix.setText(bundle.getString("MatrixFrame.jmiOpenMatrix.text")); // NOI18N
        jmMatrix.add(jmiOpenMatrix);
        jmMatrix.add(jSeparator3);

        jmiSaveMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSaveMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/save.png"))); // NOI18N
        jmiSaveMatrix.setMnemonic('s');
        jmiSaveMatrix.setText(bundle.getString("MatrixFrame.jmiSaveMatrix.text")); // NOI18N
        jmMatrix.add(jmiSaveMatrix);

        jmiSaveAsMatrix.setText(bundle.getString("MatrixFrame.jmiSaveAsMatrix.text")); // NOI18N
        jmMatrix.add(jmiSaveAsMatrix);
        jmMatrix.add(jSeparator2);

        jmiDeleteMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        jmiDeleteMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/delete.png"))); // NOI18N
        jmiDeleteMatrix.setMnemonic('d');
        jmiDeleteMatrix.setText(bundle.getString("MatrixFrame.jmiDeleteMatrix.text")); // NOI18N
        jmMatrix.add(jmiDeleteMatrix);
        jmMatrix.add(jSeparator1);

        jmExport.setMnemonic('e');
        jmExport.setText(bundle.getString("MatrixFrame.jmExport.text")); // NOI18N

        jmiToExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/excel1.png"))); // NOI18N
        jmiToExcel.setMnemonic('x');
        jmiToExcel.setText(bundle.getString("MatrixFrame.jmiToExcel.text")); // NOI18N
        jmExport.add(jmiToExcel);

        jmiToPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/pdf1.png"))); // NOI18N
        jmiToPdf.setMnemonic('p');
        jmiToPdf.setText(bundle.getString("MatrixFrame.jmiToPdf.text")); // NOI18N
        jmiToPdf.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/pdfd.png"))); // NOI18N
        jmiToPdf.setEnabled(false);
        jmExport.add(jmiToPdf);

        jmMatrix.add(jmExport);
        jmMatrix.add(jSeparator4);

        jmiClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmiClose.setMnemonic('c');
        jmiClose.setText(bundle.getString("MatrixFrame.jmiClose.text")); // NOI18N
        jmiClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCloseActionPerformed(evt);
            }
        });
        jmMatrix.add(jmiClose);

        jMenuBar1.add(jmMatrix);

        jmEdit.setMnemonic('e');
        jmEdit.setText(bundle.getString("MatrixFrame.jmEdit.text")); // NOI18N

        jmiTransposeMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmiTransposeMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hummingmatrix/v2/resources/transpose.png"))); // NOI18N
        jmiTransposeMatrix.setMnemonic('t');
        jmiTransposeMatrix.setText(bundle.getString("MatrixFrame.jmiTransposeMatrix.text")); // NOI18N
        jmEdit.add(jmiTransposeMatrix);

        jMenuBar1.add(jmEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jmiCreateNewMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreateNewMatrixActionPerformed
 // TODO add your handling code here:
}//GEN-LAST:event_jmiCreateNewMatrixActionPerformed

private void jmiCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCloseActionPerformed
    this.dispose();
}//GEN-LAST:event_jmiCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmExport;
    private javax.swing.JMenu jmMatrix;
    private javax.swing.JMenuItem jmiClose;
    private javax.swing.JMenuItem jmiCreateNewMatrix;
    private javax.swing.JMenuItem jmiDeleteMatrix;
    private javax.swing.JMenuItem jmiOpenMatrix;
    private javax.swing.JMenuItem jmiSaveAsMatrix;
    private javax.swing.JMenuItem jmiSaveMatrix;
    private javax.swing.JMenuItem jmiToExcel;
    private javax.swing.JMenuItem jmiToPdf;
    private javax.swing.JMenuItem jmiTransposeMatrix;
    // End of variables declaration//GEN-END:variables
}
