/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

import hummingmatrix.v2.classes.ReadWriteText;
import hummingmatrix.v2.interfaces.MatrixChangeObserver;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Darko
 */
public class ProbabilityPanel extends javax.swing.JPanel implements MatrixChangeObserver{

    private ReadWriteText matrixObj;
    /**
     * Creates new form ProbabilityPanel
     */
    public ProbabilityPanel(ReadWriteText matrix) {
        initComponents();
        this.matrixObj = matrix;
        try {
            this.initResults();
        } catch (IOException ex) {
            Logger.getLogger(ProbabilityPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.matrixObj.register(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAP = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaPCA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaPS = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaPM = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtaPNA = new javax.swing.JTextArea();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hummingmatrix/v2/translation/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("label.absolutProbability.text")); // NOI18N

        jtaAP.setEditable(false);
        jtaAP.setColumns(20);
        jtaAP.setRows(5);
        jScrollPane2.setViewportView(jtaAP);

        jLabel2.setText(bundle.getString("label.probabilityCertainAffinity.text")); // NOI18N

        jtaPCA.setEditable(false);
        jtaPCA.setColumns(20);
        jtaPCA.setRows(5);
        jScrollPane3.setViewportView(jtaPCA);

        jLabel3.setText(bundle.getString("lable.probabilityOfStaying")); // NOI18N

        jtaPS.setEditable(false);
        jtaPS.setColumns(20);
        jtaPS.setRows(5);
        jScrollPane4.setViewportView(jtaPS);

        jLabel4.setText(bundle.getString("label.probabilityToMove")); // NOI18N

        jtaPM.setEditable(false);
        jtaPM.setColumns(20);
        jtaPM.setRows(5);
        jScrollPane5.setViewportView(jtaPM);

        jLabel5.setText(bundle.getString("label.probabilityOfNeighboringAffinity")); // NOI18N

        jtaPNA.setEditable(false);
        jtaPNA.setColumns(20);
        jtaPNA.setRows(5);
        jScrollPane6.setViewportView(jtaPNA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jtaAP;
    private javax.swing.JTextArea jtaPCA;
    private javax.swing.JTextArea jtaPM;
    private javax.swing.JTextArea jtaPNA;
    private javax.swing.JTextArea jtaPS;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onMatrixChange(ReadWriteText matrix) {
        this.matrixObj = matrix;
        try {
            initResults();
        } catch (IOException ex) {
            Logger.getLogger(CoefficientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initResults() throws IOException {
        Object[][] matrix = this.matrixObj.getMatrixContent();
        Object[][] qMatrix = this.matrixObj.presmetajQMatrica();
        
        float[] t = this.matrixObj.calculateProbability(matrix);
        jtaAP.setText(this.matrixObj.apsolutna_verojatnost_print);
        
        HashMap hm = this.matrixObj.verojatnostNaOdredenaSlicnost(qMatrix, t);
        String vos = this.matrixObj.convertVerojatnostNOS(hm);
        jtaPCA.setText(vos);
        
        this.matrixObj.verojatnostNaSosednaDistanca();
        jtaPNA.setText(this.matrixObj.verojatnost_na_distanca);
        
        this.matrixObj.presmetajPremini(matrix);
        jtaPM.setText(this.matrixObj.verojatnost_na_premin);
        jtaPS.setText(this.matrixObj.verojatnost_na_ostanuvanje);
    }
}
