/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

import hummingmatrix.v2.classes.ReadWriteText;

/**
 *
 * @author Darko
 */
public class ResultsPanel extends javax.swing.JPanel {

    private ReadWriteText matrixObj;
    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel(ReadWriteText matrix) {
        initComponents();
        this.matrixObj = matrix;
        resultTab.addTab("Coefficients", new CoefficientPanel(this.matrixObj));
        resultTab.addTab("Probability", new ProbabilityPanel(this.matrixObj));
        resultTab.addTab("Affinity", new AffinityPanel(this.matrixObj));
        resultTab.addTab("Diffusion", new DiffusionPanel(this.matrixObj));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultTab = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultTab, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultTab, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane resultTab;
    // End of variables declaration//GEN-END:variables
}
