/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingmatrix.v2.panels;

/**
 *
 * @author Ane
 */
public class WestPanelHolder extends javax.swing.JPanel {
    
    private String matrixName;

    /**
     * Creates new form WestPanelHolder
     */
    public WestPanelHolder(String matrixName) {
        initComponents();
        this.matrixName = matrixName;
        
    }
    
    public void addRealMatrixPanel() {
        RealMatrixPanel rmp = new RealMatrixPanel(this.matrixName);
        System.out.println(this.matrixName);
        this.add(rmp);
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
